-- WPU ITG · Supabase setup
-- Für ein eigenes Supabase-Projekt. Das Skript ist wiederholbar.

begin;

create extension if not exists pgcrypto;

create table if not exists public.itg_teachers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.itg_students (
  id uuid primary key default gen_random_uuid(),
  login_name text not null,
  display_name text not null,
  class_code text not null default 'WPU-ITG',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (login_name, class_code),
  constraint itg_students_login_format check (
    login_name ~ '^[^[:space:].]+\.[^[:space:].]+$'
  )
);

create table if not exists public.itg_events (
  id bigint generated by default as identity primary key,
  app_name text not null default 'chh_wpu_itg',
  student_id uuid references public.itg_students(id) on delete cascade,
  student text,
  client_id text not null,
  session_id text not null,
  class_code text,
  page text,
  unit text,
  path text,
  task text,
  phase text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  ts timestamptz not null default now()
);

create index if not exists itg_events_ts_idx
  on public.itg_events (ts desc);
create index if not exists itg_events_student_idx
  on public.itg_events (student_id, ts desc);
create index if not exists itg_events_client_idx
  on public.itg_events (client_id, ts desc);

create table if not exists public.itg_progress (
  id bigint generated by default as identity primary key,
  app_name text not null default 'chh_wpu_itg',
  student_id uuid not null references public.itg_students(id) on delete cascade,
  student text,
  client_id text not null,
  session_id text,
  class_code text,
  page text,
  unit text not null,
  path text not null default 'Basis',
  phase text,
  current_task text,
  completed_steps int not null default 0,
  total_steps int not null default 7,
  progress_percent int not null default 0 check (progress_percent between 0 and 100),
  correct_count int not null default 0,
  attempts_count int not null default 0,
  status text not null default 'active',
  ts timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, unit, path)
);

create index if not exists itg_progress_updated_idx
  on public.itg_progress (updated_at desc);

alter table public.itg_teachers enable row level security;
alter table public.itg_students enable row level security;
alter table public.itg_events enable row level security;
alter table public.itg_progress enable row level security;

-- Schüler-Login ohne Offenlegung der Freigabeliste. Der Klassen-/Kurscode
-- ist verpflichtend, damit Namen nicht projektweit abgefragt werden können.
create or replace function public.itg_student_login(
  p_login text,
  p_class text
)
returns table (
  student_id uuid,
  login_name text,
  display_name text,
  class_code text
)
language sql
stable
security definer
set search_path = pg_catalog, public
as $fn$
  select s.id, s.login_name, s.display_name, s.class_code
  from public.itg_students as s
  where s.active
    and lower(s.login_name) = lower(trim(p_login))
    and lower(s.class_code) = lower(trim(p_class))
  limit 1;
$fn$;

-- Maximal 50 Ereignisse pro Aufruf. Personenname und Kurs werden serverseitig
-- aus der Freigabeliste übernommen; der Browser kann sie nicht behaupten.
create or replace function public.itg_events_melden(p_events jsonb)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public
as $fn$
declare
  n integer;
begin
  if jsonb_typeof(p_events) <> 'array' then
    raise exception 'Ereignisse müssen als Liste gesendet werden.' using errcode = '22023';
  end if;

  n := jsonb_array_length(p_events);
  if n < 1 or n > 50 then
    raise exception 'Pro Aufruf sind 1 bis 50 Ereignisse erlaubt.' using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_events) as e(student_id uuid, event_type text, payload jsonb)
    left join public.itg_students s on s.id = e.student_id and s.active
    where s.id is null
      or e.event_type not in (
        'session_start', 'session_end', 'heartbeat', 'overview_open',
        'unit_open', 'phase_open', 'phase_complete', 'answer', 'final_test'
      )
      or octet_length(coalesce(e.payload, '{}'::jsonb)::text) > 8192
  ) then
    raise exception 'Ungültige oder nicht freigeschaltete Ereignisdaten.' using errcode = '22023';
  end if;

  insert into public.itg_events (
    app_name, student_id, student, client_id, session_id, class_code,
    page, unit, path, task, phase, event_type, payload, ts
  )
  select
    'chh_wpu_itg', s.id, s.display_name,
    left(nullif(trim(e.client_id), ''), 80),
    left(nullif(trim(e.session_id), ''), 80),
    s.class_code, left(e.page, 80), left(e.unit, 40), left(e.path, 40),
    left(e.task, 120), left(e.phase, 40), e.event_type,
    coalesce(e.payload, '{}'::jsonb), now()
  from jsonb_to_recordset(p_events) as e(
    student_id uuid, client_id text, session_id text, page text, unit text,
    path text, task text, phase text, event_type text, payload jsonb
  )
  join public.itg_students s on s.id = e.student_id and s.active
  where nullif(trim(e.client_id), '') is not null
    and nullif(trim(e.session_id), '') is not null;

  get diagnostics n = row_count;
  if n <> jsonb_array_length(p_events) then
    raise exception 'Client- oder Sitzungskennung fehlt.' using errcode = '22023';
  end if;
  return n;
end;
$fn$;

-- Fortschritt wird ausschließlich über diesen begrenzten Upsert geschrieben.
-- UPDATE braucht dadurch keine anonym lesbare SELECT-Policy.
create or replace function public.itg_progress_speichern(p_progress jsonb)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $fn$
declare
  sid uuid;
  s public.itg_students%rowtype;
  unit_id text;
  lernpfad text;
begin
  sid := nullif(p_progress ->> 'student_id', '')::uuid;
  unit_id := upper(trim(coalesce(p_progress ->> 'unit', '')));
  lernpfad := case lower(trim(coalesce(p_progress ->> 'path', 'basis')))
    when 'erweiterung' then 'Erweiterung'
    else 'Basis'
  end;

  select * into s from public.itg_students where id = sid and active;
  if s.id is null then
    raise exception 'Person ist nicht freigeschaltet.' using errcode = '42501';
  end if;
  if unit_id !~ '^ITG-[0-9]{2}$' then
    raise exception 'Ungültige Einheit.' using errcode = '22023';
  end if;

  insert into public.itg_progress (
    app_name, student_id, student, client_id, session_id, class_code,
    page, unit, path, phase, current_task, completed_steps, total_steps,
    progress_percent, correct_count, attempts_count, status, ts, updated_at
  ) values (
    'chh_wpu_itg', s.id, s.display_name,
    left(nullif(trim(p_progress ->> 'client_id'), ''), 80),
    left(nullif(trim(p_progress ->> 'session_id'), ''), 80),
    s.class_code, left(p_progress ->> 'page', 80), unit_id, lernpfad,
    left(p_progress ->> 'phase', 40), left(p_progress ->> 'current_task', 120),
    least(7, greatest(0, coalesce((p_progress ->> 'completed_steps')::int, 0))),
    least(7, greatest(1, coalesce((p_progress ->> 'total_steps')::int, 7))),
    least(100, greatest(0, coalesce((p_progress ->> 'progress_percent')::int, 0))),
    greatest(0, coalesce((p_progress ->> 'correct_count')::int, 0)),
    greatest(0, coalesce((p_progress ->> 'attempts_count')::int, 0)),
    case when p_progress ->> 'status' = 'completed' then 'completed' else 'active' end,
    now(), now()
  )
  on conflict (student_id, unit, path) do update set
    student = excluded.student,
    client_id = excluded.client_id,
    session_id = excluded.session_id,
    class_code = excluded.class_code,
    page = excluded.page,
    phase = excluded.phase,
    current_task = excluded.current_task,
    completed_steps = excluded.completed_steps,
    total_steps = excluded.total_steps,
    progress_percent = excluded.progress_percent,
    correct_count = excluded.correct_count,
    attempts_count = excluded.attempts_count,
    status = excluded.status,
    updated_at = now();
end;
$fn$;

-- Eine Auth-Anmeldung allein reicht nicht: Nur explizit in itg_teachers
-- eingetragene Konten erhalten Zugriff auf Schüler- und Dashboarddaten.
drop policy if exists "itg teachers read membership" on public.itg_teachers;
create policy "itg teachers read membership"
  on public.itg_teachers for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "itg teacher students" on public.itg_students;
create policy "itg teacher students"
  on public.itg_students for all to authenticated
  using (exists (
    select 1 from public.itg_teachers t where t.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.itg_teachers t where t.user_id = (select auth.uid())
  ));

drop policy if exists "itg teacher events" on public.itg_events;
create policy "itg teacher events"
  on public.itg_events for select to authenticated
  using (exists (
    select 1 from public.itg_teachers t where t.user_id = (select auth.uid())
  ));

drop policy if exists "itg teacher progress" on public.itg_progress;
create policy "itg teacher progress"
  on public.itg_progress for select to authenticated
  using (exists (
    select 1 from public.itg_teachers t where t.user_id = (select auth.uid())
  ));

drop policy if exists "itg anon insert events" on public.itg_events;
drop policy if exists "itg anon insert progress" on public.itg_progress;
drop policy if exists "itg anon update progress" on public.itg_progress;

revoke all on public.itg_teachers, public.itg_students,
  public.itg_events, public.itg_progress from anon;

grant usage on schema public to anon, authenticated;
grant select on public.itg_teachers to authenticated;
grant select, insert, update, delete on public.itg_students to authenticated;
grant select on public.itg_events, public.itg_progress to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.itg_student_login(text, text) from public, anon, authenticated;
revoke all on function public.itg_events_melden(jsonb) from public, anon, authenticated;
revoke all on function public.itg_progress_speichern(jsonb) from public, anon, authenticated;

grant execute on function public.itg_student_login(text, text) to anon, authenticated;
grant execute on function public.itg_events_melden(jsonb) to anon, authenticated;
grant execute on function public.itg_progress_speichern(jsonb) to anon, authenticated;

commit;
